language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - yarn test:coverage
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master